/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordcounter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        WordCounter classUnderTest = new WordCounter();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
